### PR TITLE
Update SSPXR-Snacks.cfg

### PR DESCRIPTION
**Pull request by LouisCyfer**
- add general standard SoilRecycler to selected parts (rate = 1 snacks/seat/day, centrifuges using DeployedCrewCapacity)
- 50% boost for both greenhouses (10 snacks per day/double rate of stock lab)
- sspx-greenhouse-375-1: 30% boost EC usage and Snacks output in both modules (SoilRecycler, SnackProcessor)

### CODE REVIEW

**Comment by LouisCyfer** [comment]
The current patch rudimentary balances things and should work if snacks would, I suggest waiting to accept this PR until a Snacks update is out so I also can update my snacks-recyclers and add support for it to this patch aswell.

hope this makes sense.

**Comment by ChrisAdderley** [comment]
Fine by me, just let me know when I should merge it.

**Comment by LouisCyfer** [comment]
The idea of this patch is giving that parts a proper snacks support where RecyclerCapacity should reflect every seat in a part. Currently Snacks v1.11.5 has a bug/an issue where RecyclerCapacity & recycler efficiency doesn't opt in. Having Science Kerbals in the part decreases the converter values exponentially so having no Kerbals in the part is the best recycler result with above mentioned Snacks version.

The issue: RecyclerCapacity somehow doesn't matter so we manipulate the resources to match reasonable rates. When Snacks is fixed we might have to patch again to have parts with 1 RecyclerCapacity per seat instead manipulating the resources.

The current patch I wrote would do the desired design if Snacks would do as supposed. I will add support for my snacks-recyclers that depends on Snacks once [Angel-125](https://github.com/Angel-125) comes up with a reliable patch (hopefully soon™).

**Comment by ChrisAdderley** [comment]
Ok, merged this then.

**Comment by LouisCyfer** [comment]
I haven't added support for my snacks-recyclers yet, but will do that vice versa. Means I add SSPXr to snacks-recyclers mod support then, it also works out.

Thank you !

**Pull request merged**
