### PR TITLE
Update SSPXR-KerbalHealth.cfg

### PR DESCRIPTION
**Pull request by fraz86**
Update compatibility patch to conform to new standards of Kerbal Health v1.1. Also resolves a MM path-order problem from prior version.

### CODE REVIEW

**Comment by LouisCyfer** [comment]
suggesting a proper fix for KerbalHealth compatiblity
see [my gist](https://gist.github.com/LouisCyfer/89ccad938da43210b12ab70d59424899)

**Comment by ChrisAdderley** [comment]
Be nice to have a PR (against dev), some of that has already been addressed.

**Comment by theonegalen** [comment]
@fraz86 never use :FOR[whatever]. It causes mm to think that [whatever] mod is in there is installed, and activates all patches with :NEEDS[whatever] even if the mod isn't installed.

:AFTER[whatever] is great, because it also is conditional and only activates if [whatever] is installed.

**Comment by theonegalen** [comment]
@fraz86 if you need the patch to apply before the KH generic config activates, use :BEFORE[KerbalHealth]

**Pull request merged**
