### PR TITLE
BP9 Part Switch es-es

### PR DESCRIPTION
**Pull request by SergiRuizZarzuelo**

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
You have two separate PRs open - which is the one?

**Comment by SergiRuizZarzuelo** [comment]
Both. But BP9 Switch is no needed….

The second one is the SPER translation.

**Comment by SergiRuizZarzuelo** [comment]
https://github.com/SergiRuizZarzuelo/StationPartsExpansionRedux/tree/master/GameData/StationPartsExpansionRedux/Localization

**Comment by ChrisAdderley** [comment]
Uh, should I merge this pull request or the other one you opened?

**Comment by SergiRuizZarzuelo** [comment]
>           Uh, should I merge this pull request or the other one you opened?

This one if you prefer...

**Comment by SergiRuizZarzuelo** [comment]
Great!!! CKAN updated!
working correctly….

**Pull request merged**
