### PR TITLE
USI MKS compatibility. Again.

### PR DESCRIPTION
**Pull request by doktorjet**
ExtraplanetaryLaunchpad resources should NEVER be used when USI MKS is installed.
USI MKS force-replaces them with CRP-friendly resources!

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
Fix conflicts please, and target `dev` in the future to avoid this kind of thing.

**Comment by doktorjet** [comment]
Always miss the right branch... I'm sorry.

**Comment by ChrisAdderley** [comment]
I'm almost ready to release the next version - if you want these fixes in you'll have to rebase this to dev and fix the conflicts.

**Comment by doktorjet** [comment]
Updated RU changes for TAC LS compatibility, MKS compatibility patches not changed.

**Pull request merged**
