### PR TITLE
Russian localization (finished for all strings available)

### PR DESCRIPTION
**Pull request by doktorjet**
About 3/4 of implemented parts are done, science experiments barely started.

### CODE REVIEW

**Comment by doktorjet** [comment]
Firstly, it's AMAZING mod! Even in current unfinished state.
Though I have some questions:

1) 'Storage modules' seem to be stock 'service bays'. But is there any functional difference between 'Cargo modules' and 'Logistic modules'? It's crucial for exact translation. 
2) Is PXL-2 'experiment airlock' an experimental airlock or a separate airlock for (dangerous, explosive, etc.) experiments?
3) PPD-A2, PPD-A4 - are 'fixtures' some useful gadgets or just internal hard structure?
4) Kale (at least what I know by that name) is actually a cattle fodder. Well... I know, British are eating it, but they eat a lot of strange stuff that noone else would. Do you really mean kerbals should too?
5) Shouldn't resource names rely on CommunityResourcePack instead?

**Comment by ChrisAdderley** [comment]
Thanks!

If you're doing this now, I'll make an effort to uniformize and clean up the descriptions today. I can't promise things won't change more in the future though...

1. All the cargo bay-like modules should be "Storage Module". All the cargo containers should be "Logistics Module" for consistency. Radially attached containers will be "Cargo Container". I'll reconcile this in english soon.
2. An internal experiment airlock like the Kibo module on the ISS
3. Fixtures would colloquially mean useful internal components. Should here mean something like "it's an empty tube"
4. Yep. It's a joke on the health food craze of it here. 
5. Don't know what you mean by that. If you mean the the localization for the switchhable containers, no, they should not.

**Comment by ChrisAdderley** [comment]
Mmmk, latest commit should clean up some english localization things. That's about as final as I can make it for now.

**Comment by doktorjet** [comment]
Couple more questions:
1) 'Minor creature comforts' - is it a minimum bearable comfort for kerbals or a luxurious option of having minor creatures (pets) as additional comfort option?
2) In USI MKS 'Commodities' cargo type means mixed tank type that holds both ExoticMinerals and RareMetals. Do you really need to have separate configs for them? Those resources are never used without each other.

**Comment by ChrisAdderley** [comment]
1. The first.
2. There's other mods that use the types separately.

**Comment by doktorjet** [comment]
1) #LOC_SSPX_ScienceDef_PlantGrowth_JoolSrfLanded (first of two) - Should it be "flying high in atmosphere" instead? It's the only way to safely grab a sample of Jool atmpsphere.
2) #LOC_SSPX_ScienceDef_PlantGrowth_JoolSrfLanded (second of two) - yeah, **lol**! =) Gas giant has no surface to land on.
3) #LOC_SSPX_ScienceDef_PlantGrowth_LaytheInSpaceHigh - unfinished string

**Comment by doktorjet** [comment]
Finished all available strings. Poke me when you have more.

**Comment by doktorjet** [comment]
Updated with latest additions. 
No translations of craddle descriptions yet. Have to see them in action to describe correctly.

P.S. Why do you merge other pull requests but not mine?

**Comment by doktorjet** [comment]
It's quite unhandy to update fork from original when old pull request still hangs there...

**Comment by ChrisAdderley** [comment]
I thought you wanted to just leave this hanging and update it periodically until we got to near release. That's how I've done it with people's. If you think this is ready for an initial merge, I will do so.

**Comment by doktorjet** [comment]
_I thought you wanted to just leave this hanging and update it periodically until we got to near release._ 
Of course I'm not. I don't understand how that can be comfortable. While my pull request is hanging there I CAN'T SEE ANY CHANGES TO YOUR MASTER VERSION in my GUI client! I had to visit GitHub site manually (a loooong time after, since client said there is nothing to see) just to notice I'm 26 commits behind.
Please don't let it hang here like that. It annoys me a lot.
Will continue to work on that after merging. Thanks.

**Comment by ChrisAdderley** [comment]
Oh please. If you insist on working on translating an extremely WIP mod whose strings are constantly in flux and have only recently been nailed down, you're in for some headaches. Deal with it.
WIP PRs are a thing. They sit around and you periodically rebase and add commits. We do this frequently at work for things that are in progress and low priority. Don't assume that I can read your mind and know exactly your workflow, then be unhappy when I can't.

**Pull request merged**
